name: AI Task Router
# T016: Detects @gitaiteams mentions and triggers orchestrator

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  route:
    name: Route AI Task
    runs-on: ubuntu-latest

    # Only run if @gitaiteams is mentioned in issue body or comment
    if: |
      github.event.issue.pull_request == null &&
      (
        (github.event_name == 'issues' && contains(github.event.issue.body, '@gitaiteams')) ||
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@gitaiteams'))
      )

    permissions:
      contents: read
      issues: write
      actions: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add eyes reaction
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add eyes reaction to acknowledge mention
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            gh api --method POST \
              "/repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions" \
              -f content='eyes' || echo "Failed to add reaction"
          else
            # For issues, add reaction to the issue itself
            gh api --method POST \
              "/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/reactions" \
              -f content='eyes' || echo "Failed to add reaction"
          fi

      - name: Add trigger label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add label to track AI tasks
          gh issue edit ${{ github.event.issue.number }} \
            --add-label "trigger:ai-task" || echo "Label might already exist"

      - name: Trigger orchestrator via Claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          claude_args: |
            --allowed-tools Bash(gh:*)
          prompt: |
            You are the GitAI Teams router. A user mentioned @gitaiteams in issue #${{ github.event.issue.number }}.

            CRITICAL: You must trigger the orchestrator using repository_dispatch.

            Issue Number: ${{ github.event.issue.number }}
            Comment ID: ${{ github.event_name == 'issue_comment' && github.event.comment.id || 'none' }}
            Task: ${{ github.event_name == 'issues' && github.event.issue.body || github.event.comment.body }}

            Execute this gh command to trigger the orchestrator:
            ```bash
            gh api "repos/${{ github.repository }}/dispatches" \
              --method POST \
              -f event_type="orchestrate_task" \
              -f client_payload='{"issue_number":"${{ github.event.issue.number }}","comment_id":"${{ github.event_name == 'issue_comment' && github.event.comment.id || 0 }}","task":"${{ github.event_name == 'issues' && github.event.issue.body || github.event.comment.body }}"}'
            ```

            This will trigger the ai-task-orchestrator workflow to handle the task.

            IMPORTANT: You MUST execute the gh api command above. The CLAUDE_CODE_OAUTH_TOKEN is already available in your environment.